---
# tasks file for codedeploy

- name: "Detected {{ ansible_os_family }} based distro"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Loading config"
  include: "{{ ansible_os_family }}.yml"

- name: "Installing pip"
  pip:
    state: present
    name: "{{ item }}"
  with_items:
    - awscli

- name: "Downloading codedeploy-agent"
  get_url:
    url: "https://aws-codedeploy-{{ region }}.s3.amazonaws.com/latest/install"
    dest: /tmp/codedeploy-install
  when: codedeploy_check.failed == True

- name: "Changing permissions"
  file:
    state: file
    path: /tmp/codedeploy-install
    group: root
    owner: root
    mode: 0755
  when: codedeploy_check.failed == True


- name: "Codedeploy Install"
  become: true
  command: /tmp/codedeploy-install auto
  when: codedeploy_check.failed == True
